# docker-compose.yml
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf 