# .github/workflows/main.yml
name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Backend API image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.api # <-- CHANGED from 'dockerfile'
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/vehicle-api:latest

    - name: Build and push Frontend Web image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.web # <-- CHANGED from 'dockerfile'
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/vehicle-web:latest